import type { Metadata } from "next";
import "./globals.css";
import { TooltipProvider } from "@/components/ui/tooltip";
import { DocumentProvider } from "@/contexts/DocumentContext";
import { Toaster } from "@/components/ui/toaster";
import { Toaster as Sonner } from "@/components/ui/sonner";




export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


   // ${geistSans.variable} ${geistMono.variable} 

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`
          
      antialiased`}
      >
          <TooltipProvider>
            <DocumentProvider>
              <Toaster />
              <Sonner />
              {children}
            </DocumentProvider>
          </TooltipProvider>
      </body>
    </html>
  );
}
